// Writes the current package version + a fresh build hash into:
//   - public/version.json   -> served statically, polled at runtime
//   - src/build-info.ts     -> bundled into the app
//
// version.json also carries the remote KILL SWITCH fields: status, message,
// newUrl. Those are owner-controlled — this script PRESERVES whatever is
// already in public/version.json so a build never resets them.
//
// To revoke every copy of the app:
//   1. Edit public/version.json — set "status": "revoked"
//      (optionally set "message" and "newUrl" to point users to the new app).
//   2. Commit and push. On next online launch every copy locks itself,
//      clears its cached data, and shows the retired screen.
//   To bring it back, set "status" to "active".
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { randomBytes } from 'node:crypto';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const versionPath = join(root, 'public', 'version.json');

// Preserve owner-controlled kill-switch fields across builds.
let prev = {};
try {
  prev = JSON.parse(readFileSync(versionPath, 'utf8'));
} catch {
  prev = {};
}

const core = {
  version: pkg.version,
  buildHash: randomBytes(6).toString('hex'),
  builtAt: new Date().toISOString(),
};

const versionInfo = {
  ...core,
  status: prev.status === 'revoked' ? 'revoked' : 'active',
  message: typeof prev.message === 'string' ? prev.message : '',
  newUrl: typeof prev.newUrl === 'string' ? prev.newUrl : '',
};

writeFileSync(versionPath, JSON.stringify(versionInfo, null, 2) + '\n');

writeFileSync(
  join(root, 'src', 'build-info.ts'),
  `// AUTO-GENERATED by scripts/stamp-version.mjs — do not edit by hand.\n` +
    `export const BUILD_INFO = ${JSON.stringify(core, null, 2)} as const;\n`,
);

console.log(
  `Stamped build ${core.version} (${core.buildHash}) — status: ${versionInfo.status}`,
);
