// Writes the current package version + a fresh build hash into:
//   - public/version.json   -> served statically, polled at runtime
//   - src/build-info.ts     -> bundled into the app
// The auto-update banner compares the two: when the deployed version.json
// has a different buildHash than the one bundled in the running app, a new
// deploy is available.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { randomBytes } from 'node:crypto';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

const info = {
  version: pkg.version,
  buildHash: randomBytes(6).toString('hex'),
  builtAt: new Date().toISOString(),
};

writeFileSync(
  join(root, 'public', 'version.json'),
  JSON.stringify(info, null, 2) + '\n',
);

writeFileSync(
  join(root, 'src', 'build-info.ts'),
  `// AUTO-GENERATED by scripts/stamp-version.mjs — do not edit by hand.\n` +
    `export const BUILD_INFO = ${JSON.stringify(info, null, 2)} as const;\n`,
);

console.log(`Stamped build ${info.version} (${info.buildHash})`);
