// AUTO-GENERATED by scripts/stamp-version.mjs — do not edit by hand.
export const BUILD_INFO = {
  "version": "1.0.0",
  "buildHash": "e15fafb2d51c",
  "builtAt": "2026-05-23T19:27:27.989Z"
} as const;
