// AUTO-GENERATED by scripts/stamp-version.mjs — do not edit by hand.
export const BUILD_INFO = {
  "version": "1.0.0",
  "buildHash": "90e10f8a82aa",
  "builtAt": "2026-05-22T15:54:26.687Z"
} as const;
