// AUTO-GENERATED by scripts/stamp-version.mjs — do not edit by hand.
export const BUILD_INFO = {
  "version": "1.0.0",
  "buildHash": "72f30e7d39fb",
  "builtAt": "2026-05-23T21:47:56.254Z"
} as const;
